### ISSUE TITLE
docker build fails for features=jito-solana

### ISSUE THREAD

**Issue by flahpah** [jito-foundation/geyser-grpc-plugin#23]
Here are the errors

   --> server/src/geyser_grpc_plugin.rs:297:85
    |
297 |                         transaction: Some(tx.transaction.to_versioned_transaction().into()),
    |                                                                                     ^^^^ the trait `From<solana_sdk::transaction::VersionedTransaction>` is not implemented for `jito_geyser_protos::solana::storage::confirmed_block::Transaction`
    |
    = help: the following other types implement trait `From<T>`:
              <jito_geyser_protos::solana::storage::confirmed_block::Transaction as From<solana_sdk::transaction::Transaction>>
              <jito_geyser_protos::solana::storage::confirmed_block::Transaction as From<solana_sdk::transaction::versioned::VersionedTransaction>>
    = note: required because of the requirements on the impl of `Into<jito_geyser_protos::solana::storage::confirmed_block::Transaction>` for `solana_sdk::transaction::VersionedTransaction`

error[E0277]: the trait bound `TransactionStatusMeta: From<solana_transaction_status::TransactionStatusMeta>` is not satisfied
   --> server/src/geyser_grpc_plugin.rs:298:71
    |
298 |                         meta: Some(tx.transaction_status_meta.clone().into()),
    |                                                                       ^^^^ the trait `From<solana_transaction_status::TransactionStatusMeta>` is not implemented for `TransactionStatusMeta`
    |
    = help: the following other types implement trait `From<T>`:
              <TransactionStatusMeta as From<StoredTransactionStatusMeta>>
              <TransactionStatusMeta as From<solana_transaction_status::TransactionStatusMeta>>
    = note: required because of the requirements on the impl of `Into<TransactionStatusMeta>` for `solana_transaction_status::TransactionStatusMeta`

error[E0277]: the trait bound `jito_geyser_protos::solana::storage::confirmed_block::Transaction: From<solana_sdk::transaction::VersionedTransaction>` is not satisfied
   --> server/src/geyser_grpc_plugin.rs:310:85
    |
310 |                         transaction: Some(tx.transaction.to_versioned_transaction().into()),
    |                                                                                     ^^^^ the trait `From<solana_sdk::transaction::VersionedTransaction>` is not implemented for `jito_geyser_protos::solana::storage::confirmed_block::Transaction`
    |
    = help: the following other types implement trait `From<T>`:
              <jito_geyser_protos::solana::storage::confirmed_block::Transaction as From<solana_sdk::transaction::Transaction>>
              <jito_geyser_protos::solana::storage::confirmed_block::Transaction as From<solana_sdk::transaction::versioned::VersionedTransaction>>
    = note: required because of the requirements on the impl of `Into<jito_geyser_protos::solana::storage::confirmed_block::Transaction>` for `solana_sdk::transaction::VersionedTransaction`

error[E0277]: the trait bound `TransactionStatusMeta: From<solana_transaction_status::TransactionStatusMeta>` is not satisfied
   --> server/src/geyser_grpc_plugin.rs:311:71
    |
311 |                         meta: Some(tx.transaction_status_meta.clone().into()),
    |                                                                       ^^^^ the trait `From<solana_transaction_status::TransactionStatusMeta>` is not implemented for `TransactionStatusMeta`
    |
    = help: the following other types implement trait `From<T>`:
              <TransactionStatusMeta as From<StoredTransactionStatusMeta>>
              <TransactionStatusMeta as From<solana_transaction_status::TransactionStatusMeta>>
    = note: required because of the requirements on the impl of `Into<TransactionStatusMeta>` for `solana_transaction_status::TransactionStatusMeta`

error[E0277]: the trait bound `Reward: From<solana_transaction_status::Reward>` is not satisfied
   --> server/src/geyser_grpc_plugin.rs:341:72
    |
341 |                     rewards: block.rewards.iter().map(|r| (*r).clone().into()).collect(),
    |                                                                        ^^^^ the trait `From<solana_transaction_status::Reward>` is not implemented for `Reward`
    |
    = help: the trait `From<solana_transaction_status::Reward>` is implemented for `Reward`
    = note: required because of the requirements on the impl of `Into<Reward>` for `solana_transaction_status::Reward`

**Comment by flahpah** [comment]
I believe the cause is the protos package uses solana-account-decoder = "~1.14" and solana-transaction-status = "~1.14" which isnt compatible with the feature flag jito-solana.

**Comment by esemeniuc** [comment]
Can you provide a code snippet of how geyser is being used?

**Comment by flahpah** [comment]
Hello, just doing the following to build the server for validator plugin

cargo b -r --features jito-solana

Does it work on your computer?

**Comment by esemeniuc** [comment]
You should checkout the `v1.14` branch. I've made a PR to master to fix this issue in the future

**Comment by esemeniuc** [comment]
@flahpah is v1.14 branch working for you?
