### ISSUE TITLE
Cannot compile with v1.17

### ISSUE THREAD

**Issue by Cetipo** [jito-foundation/geyser-grpc-plugin#35]
Trying to compile geyser-grpc-plugin v1.17 with ` ./f jito-solana`
See this error:

#12 [stage-0 7/7] RUN --mount=type=cache,mode=0777,target=/geyser-grpc-plugin/target     --mount=type=cache,mode=0777,target=/usr/local/cargo/registry     --mount=type=cache,mode=0777,target=/usr/local/cargo/git     if [ -z "jito-solana" ] ; then       cargo build --release && cp target/release/libgeyser* ./container-output;     else       cargo build --release --features "jito-solana" && cp target/release/libgeyser* ./container-output;     fi
#12 0.156 info: syncing channel updates for '1.73.0-x86_64-unknown-linux-gnu'
#12 0.451 info: latest update on 2023-10-05, rust version 1.73.0 (cc66ad468 2023-10-03)
#12 0.451 info: downloading component 'cargo'
#12 0.529 info: downloading component 'clippy'
#12 0.571 info: downloading component 'rust-std'
#12 0.886 info: downloading component 'rustc'
#12 1.642 info: downloading component 'rustc-dev'
#12 2.618 info: downloading component 'rustfmt'
#12 2.653 info: installing component 'cargo'
#12 3.298 info: installing component 'clippy'
#12 3.582 info: installing component 'rust-std'
#12 5.625 info: installing component 'rustc'
#12 9.883 info: installing component 'rustc-dev'
#12 16.77 info: installing component 'rustfmt'
#12 17.11 error: none of the selected packages contains these features: jito-solana
#12 ERROR: process "/bin/sh -c if [ -z \"$features\" ] ; then       cargo build --release && cp target/release/libgeyser* ./container-output;     else       cargo build --release --features \"$features\" && cp target/release/libgeyser* ./container-output;     fi" did not complete successfully: exit code: 101
------

**Comment by buffalu** [comment]
jito-solana flag was deprecated
